version: '3.8'

services:
  nest-app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_NAME: nestDB
    volumes:
      - .:/usr/src/app
      # remove node_modules volume

  postgres:
    image: postgres:15
    container_name: nest-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nestDB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
